name: Build and Push Docker Image

on:
  push :
    branches:
      - docker
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPO: nutrify-dicoding
      IMAGE_NAME: nutrify-server
      IMAGE_VERSION: latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_REGISTRY_USER }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.GITHUB_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
  
      - name: Deploy on Render.com
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
            curl "$deploy_url"
